### PR TITLE
add forbole

### PR DESCRIPTION
**Pull request by kwunyeung**

### CODE REVIEW

**Comment by karzak** [comment]
Mind resubmitting with 10000000000000 tokens (10x power)?

**Comment by kwunyeung** [comment]
I was thinking leaving some tokens in the account for operations. It must be `10000000000000ukva` now?

**Comment by karzak** [comment]
10000000000000 was just so the network comes up faster. If you want an additional amount for operations that’s fine too.

**Comment by kwunyeung** [comment]
I have updated it anyway. Maybe I can get some tokens from the faucet if it will work. Or I can unbond some after live. It only takes 3 days to unbond on testnet which will be ok.

**Pull request closed without merging**
