### PR TITLE
feat: gentx for DokiaCapital-ION

### PR DESCRIPTION
**Pull request by mabalaru**

### CODE REVIEW

**Comment by mabalaru** [comment]
Hello @karzak 
Is this ok. I recreated the gentx.
Thanks

**Comment by karzak** [comment]
This is fine, I just would like you to submit with 10000000000000 tokens so that you will have more voting power and the network comes online faster.

**Comment by mabalaru** [comment]
Of sorry. I was thinking I submitted with wrong value. I will do that in max 2hrs with the new value.

**Comment by mabalaru** [comment]
I hope this is ok, I removed 1st gentx and made a new one.

**Pull request closed without merging**
